# Generated by Django 5.2.13 on 2026-04-11 06:13

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumenManajerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('komponen', models.CharField(choices=[('kurikulum', 'Pengelolaan Kurikulum'), ('ketenagaan', 'Pengelolaan Pendidik & Tenaga Kependidikan'), ('kesiswaan', 'Pengelolaan Kesiswaan'), ('sarana', 'Pengelolaan Sarana Prasarana'), ('pembiayaan', 'Pengelolaan Pembiayaan'), ('humas', 'Pengelolaan Hubungan Masyarakat'), ('layanan_khusus', 'Pengelolaan Layanan Khusus'), ('penjaminan_mutu', 'Sistem Penjaminan Mutu')], max_length=20)),
                ('standar_snp', models.CharField(blank=True, choices=[('isi', 'Standar Isi'), ('proses', 'Standar Proses'), ('lulusan', 'Standar Kompetensi Lulusan'), ('pendidik', 'Standar Pendidik & Tenaga Kependidikan'), ('sarana', 'Standar Sarana Prasarana'), ('pengelolaan', 'Standar Pengelolaan'), ('pembiayaan', 'Standar Pembiayaan'), ('penilaian', 'Standar Penilaian')], max_length=20)),
                ('indikator', models.TextField()),
                ('bobot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Instrumen Supervisi Manajerial',
            },
        ),
        migrations.CreateModel(
            name='InstrumenSupervisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('komponen', models.CharField(choices=[('perencanaan', 'Perencanaan Pembelajaran'), ('pelaksanaan', 'Pelaksanaan Pembelajaran'), ('penilaian', 'Penilaian Pembelajaran'), ('tindak_lanjut', 'Tindak Lanjut')], max_length=20)),
                ('indikator', models.TextField()),
                ('bobot', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Instrumen Supervisi',
            },
        ),
        migrations.CreateModel(
            name='Madrasah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npsn', models.CharField(max_length=8, unique=True, verbose_name='NPSN')),
                ('nama', models.CharField(max_length=200)),
                ('jenis', models.CharField(choices=[('RA', 'Raudlatul Athfal (RA)'), ('MI', 'Madrasah Ibtidaiyah'), ('MTs', 'Madrasah Tsanawiyah'), ('MA', 'Madrasah Aliyah')], max_length=3)),
                ('status', models.CharField(choices=[('Negeri', 'Negeri'), ('Swasta', 'Swasta')], max_length=7)),
                ('alamat', models.TextField()),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=5)),
                ('telepon', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kepala_madrasah', models.CharField(max_length=100)),
                ('nip_kepala', models.CharField(max_length=18)),
                ('akreditasi', models.CharField(choices=[('A', 'A (Unggul)'), ('B', 'B (Baik)'), ('C', 'C (Cukup)')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Madrasah',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUPTK', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(blank=True, max_length=18)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('pendidikan_terakhir', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=100)),
                ('tahun_lulus', models.IntegerField()),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('PPPK', 'PPPK'), ('Honorer', 'Honorer'), ('GTY', 'GTY')], max_length=50)),
                ('sertifikasi', models.BooleanField(default=False)),
                ('bidang_studi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gurus', to='supervision.madrasah')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=18, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('pangkat', models.CharField(max_length=50)),
                ('golongan', models.CharField(max_length=5)),
                ('jabatan', models.CharField(max_length=100)),
                ('wilayah_binaan', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('madrasah_binaan', models.ManyToManyField(related_name='supervisors', to='supervision.madrasah')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramKepengawasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('tujuan', models.TextField()),
                ('target', models.TextField()),
                ('jadwal', models.TextField()),
                ('metode', models.TextField()),
                ('indikator_keberhasilan', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('selesai', 'Selesai'), ('evaluasi', 'Evaluasi')], default='draft', max_length=20)),
                ('file_program', models.FileField(blank=True, upload_to='program_kepengawasan/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Program Kepengawasan',
            },
        ),
        migrations.CreateModel(
            name='HasilSupervisiManajerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('nilai_per_indikator', models.JSONField(default=dict)),
                ('nilai_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('predikat', models.CharField(blank=True, max_length=20)),
                ('nilai_kurikulum', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_ketenagaan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_kesiswaan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_sarana', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_pembiayaan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_humas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_layanan_khusus', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nilai_penjaminan_mutu', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rekomendasi', models.TextField()),
                ('tindak_lanjut', models.TextField(blank=True)),
                ('file_pendukung', models.FileField(blank=True, upload_to='supervisi_manajerial/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.madrasah')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Hasil Supervisi Manajerial',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='HasilSupervisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('nilai_per_indikator', models.JSONField(default=dict)),
                ('nilai_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('predikat', models.CharField(blank=True, max_length=20)),
                ('rekomendasi', models.TextField()),
                ('tindak_lanjut', models.TextField(blank=True)),
                ('file_pendukung', models.FileField(blank=True, upload_to='supervisi_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.guru')),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.madrasah')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.supervisor')),
            ],
            options={
                'verbose_name_plural': 'Hasil Supervisi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='TagihanPengawas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_tagihan', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jatuh_tempo', models.DateField()),
                ('deskripsi', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dibayar', 'Dibayar'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('file_tagihan', models.FileField(blank=True, upload_to='tagihan/')),
                ('bukti_bayar', models.FileField(blank=True, upload_to='bukti_bayar/')),
                ('catatan', models.TextField(blank=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.madrasah')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='PemantauanSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standar', models.CharField(choices=[('isi', 'Standar Isi'), ('proses', 'Standar Proses'), ('lulusan', 'Standar Kompetensi Lulusan'), ('pendidik', 'Standar Pendidik & Tenaga Kependidikan'), ('sarana', 'Standar Sarana Prasarana'), ('pengelolaan', 'Standar Pengelolaan'), ('pembiayaan', 'Standar Pembiayaan'), ('penilaian', 'Standar Penilaian')], max_length=20)),
                ('status', models.CharField(choices=[('belum', 'Belum Terpenuhi'), ('sebagian', 'Sebagian Terpenuhi'), ('terpenuhi', 'Terpenuhi'), ('unggul', 'Unggul')], default='belum', max_length=10)),
                ('skor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('catatan', models.TextField(blank=True)),
                ('rekomendasi', models.TextField(blank=True)),
                ('tahun', models.IntegerField()),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemantauan_snp', to='supervision.madrasah')),
            ],
            options={
                'verbose_name_plural': 'Pemantauan 8 SNP',
                'unique_together': {('madrasah', 'standar', 'tahun', 'semester')},
            },
        ),
    ]
