# Generated by Django 5.2.13 on 2026-04-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(default='Kabupaten/Kota', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.AlterModelOptions(
            name='programkepengawasan',
            options={},
        ),
        migrations.CreateModel(
            name='RekapBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField()),
                ('rata_rata_akademik', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rata_rata_manajerial', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rata_rata_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('predikat', models.CharField(blank=True, max_length=20)),
                ('jumlah_guru_disupervisi', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('madrasah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.madrasah')),
            ],
            options={
                'verbose_name_plural': 'Program Kepengawasan',
            },
        ),
    ]
